---
- name: Install&Setting NFS
  hosts: compute_node
  become: true
  tasks:
  - name: Install NFS
    ansible.builtin.apt:
      name: nfs-common
      state: present
  - name: Create share directory
    ansible.builtin.file:
      path: /clusterfs
      state: directory
  - name: Change owner
    ansible.builtin.command: chown nobody.nogroup /clusterfs
  - name: Change permission
    ansible.builtin.command: chmod -R 777 /clusterfs
  - name: Setting /etc/fstab
    ansible.builtin.lineinfile:
      path: /etc/fstab
      line: 10.0.1.10:/clusterfs    /clusterfs    nfs    defaults   0 0
  - name: Mout drive
    ansible.builtin.command: mount -a