---
- name Setting CGROUP and Start Service (HeadNode)
  hosts: head_node
  become: true

  tasks:
  - name: Setting Cgroup configuration
    ansible.builtin.copy:
      dest: /etc/slurm/cgroup.conf
      content: |
        CgroupMountpoint="/sys/fs/cgroup"
        CgroupAutomount=yes
        CgroupReleaseAgentDir="/etc/slurm/cgroup"
        AllowedDevicesFile="/etc/slurm/cgroup_allowed_devices_file.conf"
        ConstrainCores=no
        TaskAffinity=no
        ConstrainRAMSpace=yes
        ConstrainSwapSpace=no
        ConstrainDevices=no
        AllowedRamSpace=100
        AllowedSwapSpace=0
        MaxRAMPercent=100
        MaxSwapPercent=100
        MinRAMSpace=30
  - name: Setting Cgroup  allowed devices configuration
    ansible.builtin.copy:
      dest: /etc/slurm/cgroup_allowed_devices_file.conf
      content: |
        /dev/null
        /dev/urandom
        /dev/zero
        /dev/sda*
        /dev/cpu/*/*
        /dev/pts/*
        /clusterfs*  
- name: Copy configuration files to share drive (/clusterfs)
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: /clusterfs
      remote_src: true
    with_items:
      - /etc/slurm/slurm.conf
      - /etc/slurm/cgroup.conf
      - /etc/slurm/cgroup_allowed_devices_file.conf
      - /etc/munge/munge.key
  - name: Start system services
    ansible.builtin.command: "{{ item }}"
    with_items:
      - systemctl enable munge
      - systemctl start munge
      - systemctl enable slurmd
      - systemctl start slurmd
      - systemctl enable slurmctld
      - systemctl start slurmctld
  - name: Reboot system
    ansible.builtin.reboot: